[general]
import = ["~/.config/alacritty/themes/themes/coolnight.toml"]
[env]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

# opacity = 1
opacity = 0.5
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
# normal.family = "UbuntuMono Nerd Font Mono"
# size = 19

size = 19
[colors]
draw_bold_text_with_bright_colors = true
