[general]
import = ["~/.config/alacritty/themes/themes/coolnight.toml"]
[env]
TERM = "xterm-256color"
[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

# opacity = 1
opacity = 1.00
blur = true

option_as_alt = "Both"

[font]
# normal.family = "UbuntuMono Nerd Font Mono"
# size = 19
# normal.family = "MesloLGS Nerd Font Mono"
# normal.family = "CaskaydiaCove Nerd Font Mono"

 normal.family = "DankMono Nerd Font"

# normal.family = "Cascadia Code"
size = 23
bold.style = "Bold"

[colors]
draw_bold_text_with_bright_colors = true
